ALTER TABLE Book ALTER COLUMN OriginalPrice TYPE numeric(10,2);
ALTER TABLE Book ALTER COLUMN Price TYPE numeric(10,2);

ALTER TABLE ORDERS ALTER COLUMN OrderTotal TYPE numeric(10,2);
ALTER TABLE ORDERS ALTER COLUMN OrderTotal SET NOT NULL;